export type EssayParagraph =
  | string
  | { type: "hook"; text: string }
  | { type: "smallcaps"; prefix: string; text: string }
  | { type: "body"; text: string }
  | { type: "pull"; text: string }
  | { type: "closing"; text: string };

export type Essay = { title: string; paragraphs: EssayParagraph[] };

export const essays: Record<string, Essay> = {
  "building-and-leading-design-organisations": {
    title: "Building and leading design organisations",
    paragraphs: [
      { type: "hook", text: "Design leadership isn't about design. It's about creating clarity." },
      { type: "body", text: "I didn't arrive at that cleanly. I learned it by doing, and by getting lots of it wrong first." },
      { type: "smallcaps", prefix: "The first move", text: " wasn't a strategy deck. It was conversations. Engineering and product are the two functions design collaborates with most closely, and I needed them to see design as their biggest ally, not another layer of process. So I went to the people actually building the product, individually and in small working groups, and I listened. What's frustrating you? Where are you losing time? What do you actually need from design? In parallel, I introduced a foundational design system built on MUI. Not because it was perfect, but because engineers needed usable components immediately. Nothing glamorous. Just the components every engineer was rebuilding from scratch, in slightly different ways, in slightly different files, in slightly different colors. Start with what unblocks people. At the same time we ran the first accessibility assessment the platform had ever had, created the first guidelines, and worked with engineering to start tackling the issues. Necessary work. The unglamorous kind that makes everything else possible." },
      { type: "smallcaps", prefix: "The harder work", text: " was cultural. Building a design function means hiring for something you can't fully write in a job spec. I look for ambition and humbleness in the same person, someone who pushes limits because they genuinely care about the experience they're creating, but who also knows they don't own design. Product is a team sport. Designers need to facilitate, advocate, sometimes absorb frustration that isn't really about them. That last one, by the way, is more of a skill than it sounds." },
      { type: "body", text: "Getting that mix wrong is expensive. I've interviewed designers who were exceptional and bright but would struggle inside the specific dynamics of a particular squad. Culture fit sounds soft until you've spent months managing the fallout of a poor one. And even when you get the hiring right, leading a team is its own ongoing education." },
      { type: "body", text: "I've also had to unlearn things. Early on, I held on too tightly. To decisions, to quality control, to the shape of the work. Delegating felt like risk, and if I'm honest, it often felt faster to just do it myself the way I wanted it done. Which is a perfectly reasonable instinct and also a very efficient way to become the thing that slows everything down. What I had to learn was that delegating isn't just handing something over. It's communicating your own needs clearly, giving and receiving feedback in a new context, and trusting someone else's process while you focus on the bigger picture. That shift takes time. But once it happens, everything changes. When you give people genuine ownership and genuine information, they don't just perform better. They become more attached to the mission." },
      { type: "pull", text: "Clarity builds trust. Trust builds autonomy. Autonomy builds teams that don't need you in every decision. Which is exactly what you want." },
      { type: "smallcaps", prefix: "The moment design", text: " becomes strategic isn't when design gets a seat at the table. It's when design starts defining the table. When you're working with a CPTO to articulate product vision, not to deliver interfaces for someone else's vision. When the function isn't waiting to be told what to build, but is part of the conversation about what matters and why." },
      { type: "body", text: "That's what I'm building every time. Not a design team. A design function with the operating model, the relationships, the clarity, and the culture to actually move the product forward." },
      { type: "closing", text: "At the end of the day, it's just pixels. But the people who make them aren't." },
    ],
  },
  "strategic-design-leadership": {
    title: "Strategic design leadership",
    paragraphs: [
      { type: "hook", text: "Design becomes strategic when the designer stops waiting to be included and starts making themselves impossible to exclude." },
      "That sounds simple. It isn't.",
      { type: "smallcaps", prefix: "Most design leaders", text: " don't have a seat at the table because they haven't raised their voice when it mattered. Product managers, engineers, senior leaders. They are loud. They are confident. They are passionate. They have opinions about roadmaps, timelines, and the precise shade of urgency that should apply to any given Friday afternoon. And for someone wired to listen and observe, it can be hard to stop the room and say: wait, I have something to say here. I had to learn to do that. It wasn't natural to me." },
      { type: "smallcaps", prefix: "The first step", text: " is understanding what strategic design leadership actually requires, and it starts with where your attention lives. An IC designer is close to the squad, close to the design files, hands on the work that is happening right here right now. A design leader moves away from that. Less time designing, more time setting direction. Less time on specific features, more time on the overall product vision. More time with senior leadership and the C-suite, gathering client insights and market signals, making sure design is pointed in the right direction. You zoom out. Way out. And the hardest part of that transition is staying credible while doing it. I have regular catchups with my designers where we connect the work they're shaping to the bigger picture, how it moves the needle, how it fits with what other teams and regions are building. I upskill constantly, especially now with AI changing what design and prototyping look like. And when I don't know something, I say so. I've found that honesty about the limitations of my knowledge earns more trust than filling the silence with something vague." },
      { type: "pull", text: "Credibility gets you into the room. But outcomes keep you there." },
      "The clearest example of this came at Secure Code Warrior when the CPTO challenged me to rethink the product from scratch. Not iterate on what existed. Start over. With his support I ran focused design workshops with a small group of key stakeholders, and we reimagined the entire product experience. What came out of that work was a vision that unified the company in a way it hadn't been before. For once every internal team had a common goal and a shared picture of where we were going. The vision introduced a cleaner product identity, new ways of thinking about the learner experience including small mascots that accompanied developers through their journey, and more robust dashboards and risk management tools for security leaders. That work became the foundation for everything that followed. Flows were split into smaller scopes, version one of each became the new experience, and the old product has been gradually replaced ever since. Those foundational blocks also enabled this year's vision work, which includes AI and repositions the company from a learning platform to a holistic developer risk solution. At Origin Markets the strategic contribution came earlier and differently, as the first designer in the room helping founders translate an ambitious idea into a product that real institutions could use. Different companies, different moments. The same underlying shift: design moving from delivery to direction.",
      { type: "smallcaps", prefix: "The tricky thing", text: " about trust is that you have to be vigilant about maintaining it. Every time leadership changes, which in a scaling company happens more than you'd expect, you start from scratch. A new leader brings new expectations, a new communication style, a new mental model of what product should be. Each time I read the room fast, adapt, and begin again. Working remotely across regions adds its own layer. When your direct leadership sits in APAC and you're in EMEA, the natural moments that build trust simply don't exist. You have to engineer the moments that used to just happen." },
      { type: "smallcaps", prefix: "And then there's", text: " the pressure that tests whether the strategic position you've built actually holds. The feature was needed yesterday. Just add a button for now. We'll fix it later. Design is often the first thing compressed when timelines tighten. My approach is to de-escalate first, a bit of humour, a moment for everyone to breathe, and then back to the facts. We have accessibility standards, a design system, UX principles. These aren't bureaucracy, they're guardrails that stop us breaking something upstream while fixing something downstream. I also try to name what kind of decision we're making: quick win, monitored experiment, or something that will live in the product for years. That question alone shifts people from defending a position to solving a problem together. My background in front end development helps here too. I speak the language of engineers, understand their constraints, and find solutions that are sound, realistic, and still creative enough to matter. Tech people are problem solvers first. Frame the problem clearly and they want to help." },
      { type: "smallcaps", prefix: "Ultimately, the measure", text: " of a strategic design leader isn't how loudly they speak in the room. It's what happens when they're not in the room. I measure my success by how little the team needs me in the day to day. If I've done my job well, I've raised designers who make strong decisions independently, who connect their work to business value without being prompted, and who are growing into leaders themselves. Not to make myself indispensable, but to make strong designers indispensable." },
      { type: "closing", text: "That's what it means to lead strategically. Not the prettiest interfaces. The clearest thinking, building the conditions for great work to happen with or without you." },
    ],
  },
  "systems-thinking": {
    title: "Systems thinking",
    paragraphs: [
      { type: "hook", text: "Something I noticed early in my career is that most problems that look like design problems are not design problems. They are symptoms of something upstream. A button in the wrong place is rarely about the button." },
      "When I joined Secure Code Warrior the platform looked fragmented. Inconsistent UI, buried functionality, no clear navigation. The instinct in that situation is to redesign. But when I looked closer, the real issue wasn't aesthetic. Each team had been solving their own problems locally, in isolation, without anyone asking how their piece connected to the others. The product had accumulated rather than evolved. You can't redesign your way out of that. You have to understand the whole before you touch any of the parts.",
      "I learned that lesson the hard way too. Early on, a feature was shipped as a quick experiment, disconnected from the rest of the platform but functional enough to satisfy a need. Two clients adopted it. When we tried to deprecate it, they refused to move. Years later it still lives in the platform, creating friction in the new experience we are trying to build. A small decision made without asking what happens if this stays forever turned into a structural constraint we still work around today.",
      { type: "pull", text: "Nobody scheduled a meeting to create a permanent constraint. It just accumulated, one reasonable decision at a time, until the system had opinions of its own." },
      "That is what systems thinking is. The habit of asking what is actually connected here, and what breaks if I pull this thread. Not a methodology. Just a way of seeing before acting.",
      "The same thinking runs through computer science. Programming paradigms are essentially techniques for structuring how you approach problems, giving form to solutions before a single line of code is written. When I moved from front end development into product design, that instinct came with me. The medium changed but the questions didn't.",
      { type: "smallcaps", prefix: "What I've come", text: " to understand is that systems don't just fragment at the product level. They fragment at the organisational level first, and that's the harder problem to see. At Secure Code Warrior, as the team scaled across regions, something subtle started to happen. Teams weren't just building things differently. They were understanding the system differently. The same product principles were being interpreted in slightly different ways depending on context and location. Nobody was wrong exactly. But when mental models drift, implementations follow. The visible symptom is inconsistency in the product. The actual problem is inconsistency in how the organisation thinks about the product. Fixing the first without addressing the second just delays the next divergence." },
      { type: "smallcaps", prefix: "At Origin Markets", text: " the fragmentation was structural from the start. The workflow involved multiple institutions, each with their own partial view of the same process. No single party had full visibility of how the whole thing connected. Each optimised their own piece without understanding the dependencies. The organisation itself mirrored the workflow, fragmented by design. You couldn't fix the experience by improving the interface. You had to map the whole network of relationships before touching any of the parts." },
      { type: "smallcaps", prefix: "At Elsevier the", text: " challenge was the inverse. Mendeley was one of many products under the same parent company, each with its own identity. The systems problem wasn't fragmentation. It was calibration. How do you hold shared principles across very different products while giving each team the freedom to work in their own way? Too much standardisation kills autonomy. Too little creates a fragmented ecosystem. Getting that balance right required understanding the whole before deciding what should be shared and what should be left alone." },
      { type: "smallcaps", prefix: "Three companies, three", text: " different expressions of the same underlying problem. Systems fragment when the people inside them can't see the whole. Leadership in those environments isn't about making better decisions. It's about creating the conditions where the whole stays visible to everyone working inside it." },
      { type: "closing", text: "That feature is still there. Two clients, hundreds of developers, and a decision nobody thought twice about. That's what a system remembers even when you'd rather it forgot." },
    ],
  },
  "complex-b2b-platforms": {
    title: "Complex B2B platforms",
    paragraphs: [
      { type: "hook", text: "Real complexity isn't the number of screens or workflows. It's the number of competing realities that have to coexist." },
      "At Secure Code Warrior, a developer wants to complete a task quickly. A security leader wants visibility and governance. An executive wants evidence of risk reduction. They are all looking at the same platform but trying to achieve completely different outcomes. The complexity isn't the interface. It's designing a system that works for all of them without fragmenting under the weight of their different needs. Most B2B platforms don't become difficult because they're feature-rich. They become difficult because every feature made complete sense to someone, at some point, in a meeting that felt very important at the time. What you feel every day isn't the interface. It's the accumulation of decisions.",
      { type: "smallcaps", prefix: "I've never found", text: " this unglamorous. At Origin Markets we were helping banks and borrowers manage debt issuance processes worth hundreds of millions of pounds. At Mendeley we were supporting researchers whose work contributes to scientific progress. At Secure Code Warrior we are helping organisations reduce software risk at scale. There's nothing unglamorous about solving difficult problems that have real consequences. The constraints are different from consumer products. But the design problems are often far more interesting." },
      { type: "smallcaps", prefix: "What I've learned", text: " working across cybersecurity, fintech, and academic research is that the domains are different but the approach isn't. I start by understanding how decisions are made within a system. In cybersecurity that means understanding how developers, security teams, and leaders interact around risk. In fintech it means understanding how information moves between institutions. In research it means understanding how people collect, organise, and build on knowledge. Each domain has its own language and its own logic." },
      { type: "pull", text: "Learning that language before picking up a design tool is not optional. It's the job." },
      { type: "smallcaps", prefix: "The clearest example", text: " of this came at Origin Markets. The initial assumption was that we were building a document exchange platform. After spending time with customers something became clear. The documents weren't really the product. What mattered was the confidence between the parties exchanging them. Whether the right person had seen something. Whether someone on the other end was present and paying attention. Whether there was a human signal beneath the transaction. If we had simply digitised the existing workflow we would have built a more efficient version of the wrong thing. Understanding that shifted the challenge entirely. The product became less about forms and tasks and more about creating the conditions for trust between participants. That insight changed almost every design decision that followed." },
      "The same kind of hidden complexity showed up differently at Secure Code Warrior. One thing cybersecurity taught me is that the person creating value is often not the person receiving it. A developer completes training, fixes vulnerabilities, and changes behaviour. The security leader receives the visibility, reporting, and evidence that the organisation is reducing risk. If the platform only optimises for reporting, developers disengage. If it only optimises for developers, leaders lose confidence that the programme is working. The challenge isn't choosing one audience over the other. It's designing a system where success for one creates value for the other.",
      { type: "smallcaps", prefix: "Most designers who", text: " approach B2B for the first time underestimate the domain. They arrive expecting the interface to reveal the problem. In B2B the interface is often the least interesting part. The real challenge is understanding regulations, incentives, organisational structures, and the relationships between people who rarely sit in the same room. The best B2B designers become students of the domain first and designers second." },
      "The best B2B products feel inevitable. Not because they're simple, but because they reflect how the world actually works. The user doesn't have to translate their job into the language of the software. The software understands the shape of the work and supports it naturally. When that happens, people stop thinking about the product and start focusing on what they're trying to achieve. That's the goal.",
      { type: "closing", text: "Not a beautiful interface. A product that disappears into the work." },
    ],
  },
  "workflow-transformation": {
    title: "Workflow transformation",
    paragraphs: [
      { type: "hook", text: "Transformation is changing how work happens, not just where it happens." },
      "A lot of organisations think they're transforming a workflow when they're really just moving it from email, spreadsheets, or phone calls into software. The workflow looks different but the underlying process is exactly the same. Real transformation happens when you challenge the assumptions beneath it. Why does this step exist? Who is it serving? What decisions are actually being made here? Sometimes the biggest improvement isn't digitising a process. It's removing parts of it entirely.",
      "At Origin Markets, information moved through emails, spreadsheets, attachments, phone calls, and multiple organisations. On paper it looked chaotic. What made it interesting was that the workflow wasn't broken in the way we initially thought. The process had evolved because people were compensating for gaps elsewhere. A spreadsheet gave someone visibility they couldn't get anywhere else. A phone call created confidence before an important transaction moved forward.",
      { type: "smallcaps", prefix: "We kept trying", text: " to remove that phone call from the process because it looked redundant. Everything discussed on it already existed in the documents. When we asked why they still made it, one customer explained that the call wasn't about the information. It was about knowing the person on the other side had actually seen it and understood what it meant." },
      "That was the moment everything shifted. The value wasn't in the task. It was in the human connection behind it. The call created confidence, accountability, and a shared understanding that no document could replicate on its own. We weren't designing a document workflow. We were designing around trust between participants. The question was no longer how to remove the call. It was how to preserve the confidence the call created while improving everything around it.",
      "We knew we were looking at the wrong problem when customers kept defending parts of the workflow we assumed they wanted removed. That's usually the sign that a process is serving a purpose nobody has properly understood yet.",
      { type: "smallcaps", prefix: "Once we mapped", text: " the entire workflow and understood who was actually making decisions, we discovered several steps weren't creating value anymore. They were simply being maintained out of habit. Nobody felt responsible for challenging them so they survived. The simplification wasn't a design breakthrough. It was giving people permission to ask whether those steps were still needed." },
      "A surprising amount of process survives not because it works. Some of it survives because it was always there. Some of it survives because removing it requires a meeting nobody wants to schedule.",
      { type: "smallcaps", prefix: "Not all friction", text: " is waste. Some friction creates trust. Some creates accountability. Some forces people to stop and think before making an important decision. At Origin Markets certain interactions existed because participants wanted reassurance that the right people had seen information and understood its implications. Removing those moments would have made the process faster but potentially less trustworthy. The goal isn't eliminating friction. It's understanding which friction creates value and which creates waste. Those are very different problems." },
      { type: "smallcaps", prefix: "The people who", text: " understand a workflow best are often the people who resist changing it most. That's not because they're against change. It's usually because they can see risks that others can't. I've found resistance becomes much easier to navigate when you stop treating people as obstacles and start treating them as experts. The most successful transformations happen when the people closest to the process help shape the future state." },
      { type: "pull", text: "People rarely resist losing a workflow. They resist losing the value that workflow provided. That distinction changes everything about how you approach the conversation." },
      "A successfully transformed workflow feels uneventful from the inside. People stop talking about the process because they no longer have to think about it. Information appears where it's needed. Decisions happen at the right time. Handoffs become invisible. The workflow fades into the background and people focus on what they're trying to achieve.",
      { type: "closing", text: "A workflow is ready to be transformed when people spend more energy maintaining the process than achieving the goal it was originally created to support." },
    ],
  },
  "design-systems": {
    title: "Design systems",
    paragraphs: [
      { type: "hook", text: "A design system is a decision-making system." },
      "The components are the visible part but they're not the point. The real purpose is to help teams make consistent decisions without having to solve the same problems repeatedly. At scale, product teams spend enormous time deciding things that have already been decided elsewhere. A good design system captures those decisions so teams can focus on solving new problems instead of recreating old solutions. The bigger an organisation becomes, the less a design system is about UI and the more it becomes about alignment.",
      "I've built or contributed to design systems at three very different companies and the organisational problem was different each time. At Mendeley the challenge was consistency across products and platforms. Researchers moved between different experiences and needed them to feel connected without becoming identical. At Origin Markets there was no existing structure at all. Morpho was created to bring coherence to a product growing quickly and becoming increasingly complex. Not standardisation for its own sake, but enough structure that the product could scale without fragmenting. At Secure Code Warrior the challenge is broader still. The platform spans learning, governance, observability, and risk. The design system isn't just helping designers and engineers build interfaces. It's helping teams think about the product as a coherent whole.",
      { type: "smallcaps", prefix: "Before I joined", text: " Secure Code Warrior, a digital agency had built a design system. It lived in a design file, created without engineering input, with naming conventions, spacing, and typography that made sense for a marketing leaflet but not for a product. Engineers spent a year trying to adopt it and eventually refused. The whole project was abandoned. Significant money, significant effort, nothing to show for it." },
      "When I arrived I didn't push for a new design system. I just started building one, quietly, as part of normal work. Me, one product designer, and the engineers we were working with. The agency had delivered hundreds of symbols, elaborate states, and components for scenarios the product had never encountered and probably never would. Like receiving a very expensive fondue set for Christmas. Beautifully crafted. Completely confident in its purpose. Just not quite what anyone had asked for.",
      { type: "smallcaps", prefix: "We started with", text: " the basics. Buttons, forms, navigation, the things every engineer was rebuilding from scratch. We used them in the new code. Over time we migrated more complex repeatable components and patterns. There was pushback. Engineering questioned the overhead. Leadership questioned the need, understandably given what had just been wasted. I pushed back by making it visible. Pages assembled faster. Output became consistent without negotiation. This is how we build now. Slowly engineers started saying the same thing themselves." },
      { type: "smallcaps", prefix: "Four years later", text: " it's used by everyone and everyone contributes to it. It became a way of doing things, a standard the whole team upholds together. But we almost didn't get there. The failed project before me made the ground toxic. I was the only leader in the company pushing for it at the start, and the only reason it survived was that it stopped being a system to use and became the default way of building." },
      "A design system nobody uses tells you more about the organisation than the system itself. Most failed systems aren't rejected because the components are bad. They're rejected because nobody solved the adoption problem. If engineers weren't involved in shaping it, if it doesn't help teams move faster, or if it creates more work than it removes, people will work around it.",
      { type: "pull", text: "Adoption is a better measure of success than quality." },
      { type: "smallcaps", prefix: "What gets lost", text: " when a system is built by designers for designers is context. Teams start following patterns without understanding the reasoning behind them. The result is compliance without alignment. People doing the right thing for the wrong reason, which means the moment the pattern doesn't quite fit, nobody knows what to do." },
      "The most observable change the system eventually created at Secure Code Warrior wasn't visual. It was conversational. Teams stopped discussing how something should be built and started discussing whether it should be built at all. That's when I knew the decisions had moved to the right place in the system.",
      { type: "closing", text: "A design system succeeds when teams stop thinking about the system and start moving faster because of it." },
    ],
  },
};
