export type EssayParagraph =
  | string
  | { type: "hook"; text: string }
  | { type: "smallcaps"; prefix: string; text: string }
  | { type: "body"; text: string }
  | { type: "pull"; text: string }
  | { type: "closing"; text: string };

export type Essay = { title: string; paragraphs: EssayParagraph[] };

export const essays: Record<string, Essay> = {
  "building-and-leading-design-organisations": {
    title: "Building and leading design organisations",
    paragraphs: [
      { type: "hook", text: "Design leadership isn't about design. It's about creating clarity." },
      { type: "body", text: "I didn't arrive at that cleanly. I learned it by doing, and by getting lots of it wrong first." },
      { type: "smallcaps", prefix: "The first move", text: " wasn't a strategy deck. It was conversations. Engineering and product are the two functions design collaborates with most closely, and I needed them to see design as their biggest ally, not another layer of process. So I went to the people actually building the product, individually and in small working groups, and I listened. What's frustrating you? Where are you losing time? What do you actually need from design? In parallel, I introduced a foundational design system built on MUI. Not because it was perfect, but because engineers needed usable components immediately. Nothing glamorous. Just the components every engineer was rebuilding from scratch, in slightly different ways, in slightly different files, in slightly different colors. Start with what unblocks people. At the same time we ran the first accessibility assessment the platform had ever had, created the first guidelines, and worked with engineering to start tackling the issues. Necessary work. The unglamorous kind that makes everything else possible." },
      { type: "smallcaps", prefix: "The harder work", text: " was cultural. Building a design function means hiring for something you can't fully write in a job spec. I look for ambition and humbleness in the same person, someone who pushes limits because they genuinely care about the experience they're creating, but who also knows they don't own design. Product is a team sport. Designers need to facilitate, advocate, sometimes absorb frustration that isn't really about them. That last one, by the way, is more of a skill than it sounds." },
      { type: "body", text: "Getting that mix wrong is expensive. I've interviewed designers who were exceptional and bright but would struggle inside the specific dynamics of a particular squad. Culture fit sounds soft until you've spent months managing the fallout of a poor one. And even when you get the hiring right, leading a team is its own ongoing education." },
      { type: "body", text: "I've also had to unlearn things. Early on, I held on too tightly. To decisions, to quality control, to the shape of the work. Delegating felt like risk, and if I'm honest, it often felt faster to just do it myself the way I wanted it done. Which is a perfectly reasonable instinct and also a very efficient way to become the thing that slows everything down. What I had to learn was that delegating isn't just handing something over. It's communicating your own needs clearly, giving and receiving feedback in a new context, and trusting someone else's process while you focus on the bigger picture. That shift takes time. But once it happens, everything changes. When you give people genuine ownership and genuine information, they don't just perform better. They become more attached to the mission." },
      { type: "pull", text: "Clarity builds trust. Trust builds autonomy. Autonomy builds teams that don't need you in every decision. Which is exactly what you want." },
      { type: "smallcaps", prefix: "The moment design", text: " becomes strategic isn't when design gets a seat at the table. It's when design starts defining the table. When you're working with a CPTO to articulate product vision, not to deliver interfaces for someone else's vision. When the function isn't waiting to be told what to build, but is part of the conversation about what matters and why." },
      { type: "body", text: "That's what I'm building every time. Not a design team. A design function with the operating model, the relationships, the clarity, and the culture to actually move the product forward." },
      { type: "closing", text: "At the end of the day, it's just pixels. But the people who make them aren't." },
    ],
  },
  "strategic-design-leadership": {
    title: "Strategic design leadership",
    paragraphs: [
      "Design becomes strategic when the designer stops waiting to be included and starts making themselves impossible to exclude.",
      "That sounds simple. It isn't.",
      "Most design leaders don't have a seat at the table because they haven't raised their voice when it mattered. Product managers, engineers, senior leaders. They are loud. They are confident. They are passionate. They have opinions about roadmaps, timelines, and the precise shade of urgency that should apply to any given Friday afternoon. And for someone wired to listen and observe, it can be hard to stop the room and say: wait, I have something to say here. I had to learn to do that. It wasn't natural to me.",
      "The first step is understanding what strategic design leadership actually requires, and it starts with where your attention lives. An IC designer is close to the squad, close to the design files, hands on the work that is happening right here right now. A design leader moves away from that. Less time designing, more time setting direction. Less time on specific features, more time on the overall product vision. More time with senior leadership and the C-suite, gathering client insights and market signals, making sure design is pointed in the right direction. You zoom out. Way out. And the hardest part of that transition is staying credible while doing it. I have regular catchups with my designers where we connect the work they're shaping to the bigger picture, how it moves the needle, how it fits with what other teams and regions are building. I upskill constantly, especially now with AI changing what design and prototyping look like. And when I don't know something, I say so. I've found that honesty about the limitations of my knowledge earns more trust than filling the silence with something vague.",
      "Credibility gets you into the room. But outcomes keep you there. The clearest example of this came at Secure Code Warrior when the CPTO challenged me to rethink the product from scratch. Not iterate on what existed. Start over. With his support I ran focused design workshops with a small group of key stakeholders, and we reimagined the entire product experience. What came out of that work was a vision that unified the company in a way it hadn't been before. For once every internal team had a common goal and a shared picture of where we were going. The vision introduced a cleaner product identity, new ways of thinking about the learner experience including small mascots that accompanied developers through their journey, and more robust dashboards and risk management tools for security leaders. That work became the foundation for everything that followed. Flows were split into smaller scopes, version one of each became the new experience, and the old product has been gradually replaced ever since. Those foundational blocks also enabled this year's vision work, which includes AI and repositions the company from a learning platform to a holistic developer risk solution. At Origin Markets the strategic contribution came earlier and differently, as the first designer in the room helping founders translate an ambitious idea into a product that real institutions could use. Different companies, different moments. The same underlying shift: design moving from delivery to direction.",
      "The tricky thing about trust is that you have to be vigilant about maintaining it. Every time leadership changes, which in a scaling company happens more than you'd expect, you start from scratch. A new leader brings new expectations, a new communication style, a new mental model of what product should be. Each time I read the room fast, adapt, and begin again. Working remotely across regions adds its own layer. When your direct leadership sits in APAC and you're in EMEA, the natural moments that build trust simply don't exist. You have to engineer the moments that used to just happen.",
      "And then there's the pressure that tests whether the strategic position you've built actually holds. The feature was needed yesterday. Just add a button for now. We'll fix it later. Design is often the first thing compressed when timelines tighten. My approach is to de-escalate first, a bit of humour, a moment for everyone to breathe, and then back to the facts. We have accessibility standards, a design system, UX principles. These aren't bureaucracy, they're guardrails that stop us breaking something upstream while fixing something downstream. I also try to name what kind of decision we're making: quick win, monitored experiment, or something that will live in the product for years. That question alone shifts people from defending a position to solving a problem together. My background in front end development helps here too. I speak the language of engineers, understand their constraints, and find solutions that are sound, realistic, and still creative enough to matter. Tech people are problem solvers first. Frame the problem clearly and they want to help.",
      "Ultimately, the measure of a strategic design leader isn't how loudly they speak in the room. It's what happens when they're not in the room. I measure my success by how little the team needs me in the day to day. If I've done my job well, I've raised designers who make strong decisions independently, who connect their work to business value without being prompted, and who are growing into leaders themselves. Not to make myself indispensable, but to make strong designers indispensable.",
      "That's what it means to lead strategically. Not the prettiest interfaces. The clearest thinking, building the conditions for great work to happen with or without you.",
    ],
  },
  "systems-thinking": {
    title: "Systems thinking",
    paragraphs: [
      "Something I noticed early in my career is that most problems that look like design problems are not design problems. They are symptoms of something upstream. A button in the wrong place is rarely about the button.",
      "When I joined Secure Code Warrior the platform looked fragmented. Inconsistent UI, buried functionality, no clear navigation. The instinct in that situation is to redesign. But when I looked closer, the real issue wasn't aesthetic. Each team had been solving their own problems locally, in isolation, without anyone asking how their piece connected to the others. The product had accumulated rather than evolved. You can't redesign your way out of that. You have to understand the whole before you touch any of the parts.",
      "I learned that lesson the hard way too. Early on, a feature was shipped as a quick experiment, disconnected from the rest of the platform but functional enough to satisfy a need. Two clients adopted it. When we tried to deprecate it, they refused to move. Years later it still lives in the platform, creating friction in the new experience we are trying to build. A small decision made without asking what happens if this stays forever turned into a structural constraint we still work around today. Nobody scheduled a meeting to create a permanent constraint. It just accumulated, one reasonable decision at a time, until the system had opinions of its own.",
      "That is what systems thinking is. The habit of asking what is actually connected here, and what breaks if I pull this thread. Not a methodology. Just a way of seeing before acting.",
      "The same thinking runs through computer science. Programming paradigms are essentially techniques for structuring how you approach problems, giving form to solutions before a single line of code is written. When I moved from front end development into product design, that instinct came with me. The medium changed but the questions didn't.",
      "What I've come to understand is that systems don't just fragment at the product level. They fragment at the organisational level first, and that's the harder problem to see. At Secure Code Warrior, as the team scaled across regions, something subtle started to happen. Teams weren't just building things differently. They were understanding the system differently. The same product principles were being interpreted in slightly different ways depending on context and location. Nobody was wrong exactly. But when mental models drift, implementations follow. The visible symptom is inconsistency in the product. The actual problem is inconsistency in how the organisation thinks about the product. Fixing the first without addressing the second just delays the next divergence.",
      "At Origin Markets the fragmentation was structural from the start. The workflow involved multiple institutions, each with their own partial view of the same process. No single party had full visibility of how the whole thing connected. Each optimised their own piece without understanding the dependencies. The organisation itself mirrored the workflow, fragmented by design. You couldn't fix the experience by improving the interface. You had to map the whole network of relationships before touching any of the parts.",
      "At Elsevier the challenge was the inverse. Mendeley was one of many products under the same parent company, each with its own identity. The systems problem wasn't fragmentation. It was calibration. How do you hold shared principles across very different products while giving each team the freedom to work in their own way? Too much standardisation kills autonomy. Too little creates a fragmented ecosystem. Getting that balance right required understanding the whole before deciding what should be shared and what should be left alone.",
      "Three companies, three different expressions of the same underlying problem. Systems fragment when the people inside them can't see the whole. Leadership in those environments isn't about making better decisions. It's about creating the conditions where the whole stays visible to everyone working inside it.",
      "That feature is still there. Two clients, hundreds of developers, and a decision nobody thought twice about. That's what a system remembers even when you'd rather it forgot.",
    ],
  },
  "complex-b2b-platforms": {
    title: "Complex B2B platforms",
    paragraphs: [
      "Real complexity isn't the number of screens or workflows. It's the number of competing realities that have to coexist.",
      "At Secure Code Warrior, a developer wants to complete a task quickly. A security leader wants visibility and governance. An executive wants evidence of risk reduction. They are all looking at the same platform but trying to achieve completely different outcomes. The complexity isn't the interface. It's designing a system that works for all of them without fragmenting under the weight of their different needs. Most B2B platforms don't become difficult because they're feature-rich. They become difficult because every feature made complete sense to someone, at some point, in a meeting that felt very important at the time. What you feel every day isn't the interface. It's the accumulation of decisions.",
      "I've never found this unglamorous. At Origin Markets we were helping banks and borrowers manage debt issuance processes worth hundreds of millions of pounds. At Mendeley we were supporting researchers whose work contributes to scientific progress. At Secure Code Warrior we are helping organisations reduce software risk at scale. There's nothing unglamorous about solving difficult problems that have real consequences. The constraints are different from consumer products. But the design problems are often far more interesting.",
      "What I've learned working across cybersecurity, fintech, and academic research is that the domains are different but the approach isn't. I start by understanding how decisions are made within a system. In cybersecurity that means understanding how developers, security teams, and leaders interact around risk. In fintech it means understanding how information moves between institutions. In research it means understanding how people collect, organise, and build on knowledge. Each domain has its own language and its own logic. Learning that language before picking up a design tool is not optional. It's the job.",
      "The clearest example of this came at Origin Markets. The initial assumption was that we were building a document exchange platform. After spending time with customers something became clear. The documents weren't really the product. What mattered was the confidence between the parties exchanging them. Whether the right person had seen something. Whether someone on the other end was present and paying attention. Whether there was a human signal beneath the transaction. If we had simply digitised the existing workflow we would have built a more efficient version of the wrong thing. Understanding that shifted the challenge entirely. The product became less about forms and tasks and more about creating the conditions for trust between participants. That insight changed almost every design decision that followed.",
      "The same kind of hidden complexity showed up differently at Secure Code Warrior. One thing cybersecurity taught me is that the person creating value is often not the person receiving it. A developer completes training, fixes vulnerabilities, and changes behaviour. The security leader receives the visibility, reporting, and evidence that the organisation is reducing risk. If the platform only optimises for reporting, developers disengage. If it only optimises for developers, leaders lose confidence that the programme is working. The challenge isn't choosing one audience over the other. It's designing a system where success for one creates value for the other.",
      "Most designers who approach B2B for the first time underestimate the domain. They arrive expecting the interface to reveal the problem. In B2B the interface is often the least interesting part. The real challenge is understanding regulations, incentives, organisational structures, and the relationships between people who rarely sit in the same room. The best B2B designers become students of the domain first and designers second.",
      "The best B2B products feel inevitable. Not because they're simple, but because they reflect how the world actually works. The user doesn't have to translate their job into the language of the software. The software understands the shape of the work and supports it naturally. When that happens, people stop thinking about the product and start focusing on what they're trying to achieve. That's the goal. Not a beautiful interface. A product that disappears into the work.",
    ],
  },
};
